.travis.yml

Added artifact building to Travis so it will automatically upload builds to S3

Added artifacts built to S3

---

.travis.yml

Made S3 happy by not uploading so many files

---

src/main/interface/msp.c
src/main/interface/msp_protocol.h

PaPaYoU has graciously agreed to help us with a super helpful LUA script for editing FKF settings on the field.

Add LUA Configuration options for FKF filter and Q & R by PaPaYoU

---

README.md

Closes https://github.com/ButterFlight/butterflight/issues/26

Using the Slack invite link

---

src/main/drivers/accgyro/accgyro_imuf9001.c
src/main/drivers/accgyro/accgyro_imuf9001.h
src/main/sensors/gyro.c
src/main/target/HELIOSPRING/config.c

This is for the IMU-F target to reduce the amount of yaw drift addressing the concern of issue #29

Fix imuf calibration

---

src/main/target/HELIOSPRING/target.h

pinout was backwards

---

lib/main/STM32_USB_Device_Library/Class/hid/inc/usbd_hid_core.h
lib/main/STM32_USB_Device_Library/Class/hid/src/usbd_hid_core.c
lib/main/STM32_USB_Device_Library/Class/hid_cdc_wrapper/inc/usbd_hid_cdc_wrapper.h
lib/main/STM32_USB_Device_Library/Class/hid_cdc_wrapper/src/usbd_hid_cdc_wrapper.c
make/mcu/STM32F4.mk
src/main/drivers/serial_usb_vcp.c
src/main/fc/fc_tasks.c
src/main/target/common_fc_pre.h
src/main/vcpf4/usb_conf.h
src/main/vcpf4/usbd_conf.h

Reverts ButterFlight/butterflight#69

Revert "Revert "Add Composite CDC+HID device option.""

---

lib/main/STM32_USB_Device_Library/Class/hid_cdc_wrapper/src/usbd_hid_cdc_wrapper.c
lib/main/STM32_USB_OTG_Driver/inc/usb_defines.h
make/source.mk
src/main/drivers/serial_usb_vcp.c
src/main/fc/fc_tasks.c
src/main/interface/settings.c
src/main/pg/pg_ids.h
src/main/pg/usb.c
src/main/pg/usb.h
src/main/target/WORMFC/target.h
src/main/target/common_fc_pre.h
src/main/vcpf4/usbd_desc.c

from https://github.com/betaflight/betaflight/pull/5525
Fixes Composite device on Windows
Testing required

Enable Composite USB HID for all F4, add PG for USB device.

---

src/main/config/config_eeprom.h
src/main/interface/msp_protocol.h

- Adding "LEGACY_SA_SUPPORT" as a feature to MSP requires this increment

Increment MSP protocol, EEPROM versions for new relese

---

src/main/target/common_fc_pre.h

Restore LED support to F3

---

src/main/fc/fc_core.h
src/main/fc/fc_rc.c
src/main/fc/fc_tasks.c

this change reduces CPU load considerably when using rc_interpolation.

Rc interpolation optimization

---

src/main/build/version.h

Increment version for release

---

src/main/cms/cms_menu_imu.c

Condition #if defined(USE_GYRO_FAST_KALMAN)

ADD kalman Q and R in OSD

---

src/main/common/maths.h
src/main/flight/imu.c
src/test/unit/flight_imu_unittest.cc

Fixed branch from S0up to get it merged for the Release Candidate

[ FIXED ]  Add GPS Heading by S0up

---

src/main/flight/imu.c
src/main/sensors/compass.c

Butterflight 3.5.1 RC 
Attitude MAG correction fix.

Butterflight 3.5.1 RC MAG fix

---

src/main/target/OMNIBUSF4FW/config.c
src/main/target/OMNIBUSF4FW/target.c
src/main/target/OMNIBUSF4FW/target.h
src/main/target/OMNIBUSF4FW/target.mk

This is a port of the work that @jflyper(Thanks!) did on creating the Omnibus F4FW target for Cleanflight and Betaflight. 
I already had a user test this and it looks good so far - waiting on flight test confirmation.

Omnibus F4 Fireworks Target

---

src/main/sensors/acceleration.c
src/main/sensors/gyro.c
src/main/sensors/gyro.h

fixes CPU crash
on status cli command 
due to not synchronized 
lookupTableGyroHardware 
to  
gyroSensor_e

Butterflight 3.5.1 RC CPU crash cli > status     fix

---

src/main/sensors/boardalignment.c

Butterflight_3.5.1_RC_fix_board_orientation
fixes issues
#123
#132

Butterflight_3.5.1_RC fix board orientation

---

docs/boards/Board - CrazyBeeF3FR.md
docs/boards/Board - CrazyBeeF3FS.md
src/main/target/CRAZYBEEF3FR/target.c
src/main/target/CRAZYBEEF3FR/target.h
src/main/target/CRAZYBEEF3FR/target.mk

Add support for this board:
https://www.banggood.com/Racerstar-Crazybee-F3-Flight-Controller-4-IN-1-5A-1S-Blheli_S-ESC-Compatible-Frsky-D8-Receiver-p-1262972.html?rmmds=search

CrazyBeeF3FR - Merge from betaflight

---

src/main/fc/fc_tasks.c

imuf_107_odin  FIX fport telemetry

---

src/main/telemetry/frsky_hub.c

@orneryd 
FIX frsky_hub telemetry
ACC
HEADING

Imuf 107 odin    frsky_hub telemetry ACC HEADING fix

---

src/main/build/version.h
src/main/target/ALIENWHOOP/config.c
src/main/target/ALIENWHOOP/target.h
src/main/target/ALIENWHOOP/target.mk

Updated ALIENWHOOP defaults for Butterflight; added Blackbox

---

docs/boards/Board - SpeedyBee F4 AIO-1.md
src/main/target/SPEEDYBEEF4/config.c
src/main/target/SPEEDYBEEF4/target.c
src/main/target/SPEEDYBEEF4/target.h
src/main/target/SPEEDYBEEF4/target.mk

Hi~
I added a new target for SPEEDYBEEF4, please review! Thank you!

Add new target SPEEDYBEEF4

---

src/main/drivers/accgyro/accgyro_spi_mpu6500.c

ICM20601 Fix

---

Makefile
src/main/drivers/accgyro/accgyro_imuf9001.c
src/main/drivers/accgyro/accgyro_imuf9001.h
src/main/fc/fc_init.c
src/main/interface/cli.c
src/main/interface/cli.h
src/main/msp/msp_serial.c
src/main/startup/startup_stm32f40xx.s
src/main/target/HELIOSPRING/target.h

this allows us to no longer ship a special binary and can update specifically over USB as a passthrough

updating imuf over msp

---

src/main/interface/cli.c

fixing tpa curve output
